plugins:
  - jekyll-seo-tag
title: Kyle Dormer
description: My name is Kyle Dormer and this is my personal website. I am a Computing undergraduate at the University of Gloucestershire, specialising in web development.
locale: en_GB
