<!DOCTYPE html>
<?php 
  function sanitise($input) {
    $input = trim($input);
    $input = stripslashes($input);
    $input = htmlspecialchars($input);
    return $input;
  }

  $name = $email = $message = $display_message = '';

  if ($_SERVER["REQUEST_METHOD"] == "POST") {
    if(!empty($_POST["name"])) {
      $name = strip_input($_POST["name"]);
    }

    if(!empty($_POST["email"]) && filter_var($_POST["email"], FILTER_VALIDATE_EMAIL)) {
      $email = strip_input($_POST["email"]);
    }

    if(!empty($_POST["message"])) {
      $message = strip_input($_POST["message"]);
      $message = wordwrap($message, 100);
    }
  }

  mail("kyle@kyledormer.co.uk", $name . ' (' . $email . ') ' . 'wants to talk!', $message);
  $display_message = 'Thank you for getting in touch ' . $name 
?>

<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link rel="stylesheet" href="styles.css" />
  <title>Kyle Dormer</title>
</head>

<body>
  <script>
    document.addEventListener('DOMContentLoaded', function(event) {
      const contactButton = document.getElementById('display-contact');
      const contactForm = document.querySelector('section.contact-me');

      contactButton.addEventListener('click', function(event) {
        contactButton.style.display = 'none';
        contactForm.style.display = 'block';
      });
    });
  </script>

  <section>
    <h1>Kyle Dormer</h1>
    <p>I'm a student.</p>
    <p><a href="blog.php">Here's</a> what I've been up to.</p>
  </section>

  <button id="display-contact">Get in Touch</button>

  <section class="contact-me">
    <h2>Get in Touch</h2>
    <form action="" method="POST">
      <label for="name">Your name:</label>
      <input type="text" name="name" id="name" minlength="1" maxlength="16" />

      <label for="email">Your email:</label>
      <input type="email" name="email" id="email" maxlength="24" />

      <label for="message">Your message:</label>
      <textarea name="message" id="message" minlength="1" maxlength="2000"></textarea>

      <input type="submit" class="button" value="Send message" />
    </form>
  </section>
</body>
</html>